//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renavi.Infrastructure.Services.ServiceCabiel {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCabiel.ServicioWEBSoap")]
    public interface ServicioWEBSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPaginasMenuWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarPaginasMenuWeb(int idPaginaPadre, int idPlantilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPaginasMenuWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarPaginasMenuWebAsync(int idPaginaPadre, int idPlantilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDetallePaginaWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ObtenerDetallePaginaWeb(int idPagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDetallePaginaWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerDetallePaginaWebAsync(int idPagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarGlosarioTerminosxLetraWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarGlosarioTerminosxLetraWeb(string codLetra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarGlosarioTerminosxLetraWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarGlosarioTerminosxLetraWebAsync(string codLetra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPreguntasFrecuentesCategoriasWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarPreguntasFrecuentesCategoriasWeb(int idPlantilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPreguntasFrecuentesCategoriasWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarPreguntasFrecuentesCategoriasWebAsync(int idPlantilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPreguntasFrecuentesxCategoriaWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarPreguntasFrecuentesxCategoriaWeb(int idCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPreguntasFrecuentesxCategoriaWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarPreguntasFrecuentesxCategoriaWebAsync(int idCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarNovedadesxTipoWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarNovedadesxTipoWeb(int idPagina, int modo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarNovedadesxTipoWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarNovedadesxTipoWebAsync(int idPagina, int modo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerNovedadWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ObtenerNovedadWeb(int idPagina_ED);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerNovedadWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerNovedadWebAsync(int idPagina_ED);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarTestimonioWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarTestimonioWeb(int modo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarTestimonioWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarTestimonioWebAsync(int modo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTestimonioWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ObtenerTestimonioWeb(int idPagina_ED);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTestimonioWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerTestimonioWebAsync(int idPagina_ED);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarBannersWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarBannersWeb(int idPlantilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarBannersWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarBannersWebAsync(int idPlantilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPaginasArbolArchivosWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarPaginasArbolArchivosWeb(int idPaginaAAPadre, int idPagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPaginasArbolArchivosWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarPaginasArbolArchivosWebAsync(int idPaginaAAPadre, int idPagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPaginasxNivelWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarPaginasxNivelWeb(int idPlantilla, int idPaginaPadre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPaginasxNivelWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarPaginasxNivelWebAsync(int idPlantilla, int idPaginaPadre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarArbolArchivosxPaginaWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarArbolArchivosxPaginaWeb(int idPagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarArbolArchivosxPaginaWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarArbolArchivosxPaginaWebAsync(int idPagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarTestimonioWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int RegistrarTestimonioWeb(string cTitular, string cImagen, string cDescripion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarTestimonioWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RegistrarTestimonioWebAsync(string cTitular, string cImagen, string cDescripion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarProyectosWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarProyectosWeb(string cTipoProy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarProyectosWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarProyectosWebAsync(string cTipoProy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarDatosContactenosWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int RegistrarDatosContactenosWeb(
                    string cNombres, 
                    string cApellidos, 
                    int idTipoDoc, 
                    string cTipoDocDesc, 
                    string cNumeroDoc, 
                    string cEmail, 
                    string cTelefono, 
                    int idPais, 
                    string cPaisDesc, 
                    int idDepartamento, 
                    string cDepartamentoDesc, 
                    int idProvincia, 
                    string cProvinciaDesc, 
                    int idDistrito, 
                    string cDistritoDesc, 
                    int idConsulta, 
                    string cConsultaDesc, 
                    string cMedioDesc, 
                    int idMedio, 
                    string cDetalleConsultaDesc, 
                    int nDatosPersonales, 
                    int idProducto, 
                    string cProductoDesc, 
                    int idZonaInteres, 
                    string cZonaInteresDesc, 
                    int idPlazoComprar, 
                    string cPlazoComprarDesc, 
                    int idCuotaInicial, 
                    string cCuotaInicialDesc, 
                    string cRecibirEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarDatosContactenosWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RegistrarDatosContactenosWebAsync(
                    string cNombres, 
                    string cApellidos, 
                    int idTipoDoc, 
                    string cTipoDocDesc, 
                    string cNumeroDoc, 
                    string cEmail, 
                    string cTelefono, 
                    int idPais, 
                    string cPaisDesc, 
                    int idDepartamento, 
                    string cDepartamentoDesc, 
                    int idProvincia, 
                    string cProvinciaDesc, 
                    int idDistrito, 
                    string cDistritoDesc, 
                    int idConsulta, 
                    string cConsultaDesc, 
                    string cMedioDesc, 
                    int idMedio, 
                    string cDetalleConsultaDesc, 
                    int nDatosPersonales, 
                    int idProducto, 
                    string cProductoDesc, 
                    int idZonaInteres, 
                    string cZonaInteresDesc, 
                    int idPlazoComprar, 
                    string cPlazoComprarDesc, 
                    int idCuotaInicial, 
                    string cCuotaInicialDesc, 
                    string cRecibirEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarDatosReclamosWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int RegistrarDatosReclamosWeb(
                    string cNombres, 
                    string cApellidos, 
                    int idTipoDoc, 
                    string cTipoDocDesc, 
                    string cNumeroDoc, 
                    string cEmail, 
                    string cTelefono, 
                    string cDireccion, 
                    int idPais, 
                    string cPaisDesc, 
                    int idDepartamento, 
                    string cDepartamentoDesc, 
                    int idProvincia, 
                    string cProvinciaDesc, 
                    int idDistrito, 
                    string cDistritoDesc, 
                    int idReclamoDirigido, 
                    string cReclamoDirigidoDesc, 
                    string cDetalleReclamoDesc, 
                    int nDatosPersonales, 
                    string cNumeroruc, 
                    string cRazonSocial, 
                    string cNumeroticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarDatosReclamosWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RegistrarDatosReclamosWebAsync(
                    string cNombres, 
                    string cApellidos, 
                    int idTipoDoc, 
                    string cTipoDocDesc, 
                    string cNumeroDoc, 
                    string cEmail, 
                    string cTelefono, 
                    string cDireccion, 
                    int idPais, 
                    string cPaisDesc, 
                    int idDepartamento, 
                    string cDepartamentoDesc, 
                    int idProvincia, 
                    string cProvinciaDesc, 
                    int idDistrito, 
                    string cDistritoDesc, 
                    int idReclamoDirigido, 
                    string cReclamoDirigidoDesc, 
                    string cDetalleReclamoDesc, 
                    int nDatosPersonales, 
                    string cNumeroruc, 
                    string cRazonSocial, 
                    string cNumeroticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerParametros", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ObtenerParametros(string scodGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerParametros", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerParametrosAsync(string scodGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerListaET", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ObtenerListaET(string sRazonSocial, string sRUC, string sDepartamento, string sClasificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerListaET", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerListaETAsync(string sRazonSocial, string sRUC, string sDepartamento, string sClasificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerEntidades", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ObtenerEntidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerEntidades", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerEntidadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarRutaArchivosReclamosWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RegistrarRutaArchivosReclamosWeb(string oDatosRutaArchivoReclamosWeb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarRutaArchivosReclamosWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RegistrarRutaArchivosReclamosWebAsync(string oDatosRutaArchivoReclamosWeb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarReclamoconOTRSReclamo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ActualizarReclamoconOTRSReclamo(int numeroidTickePortalweb, string numeroTicketOTRSReclamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarReclamoconOTRSReclamo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ActualizarReclamoconOTRSReclamoAsync(int numeroidTickePortalweb, string numeroTicketOTRSReclamo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWEBSoapChannel : Renavi.Infrastructure.Services.ServiceCabiel.ServicioWEBSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWEBSoapClient : System.ServiceModel.ClientBase<Renavi.Infrastructure.Services.ServiceCabiel.ServicioWEBSoap>, Renavi.Infrastructure.Services.ServiceCabiel.ServicioWEBSoap {
        
        public ServicioWEBSoapClient() {
        }
        
        public ServicioWEBSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWEBSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWEBSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWEBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ListarPaginasMenuWeb(int idPaginaPadre, int idPlantilla) {
            return base.Channel.ListarPaginasMenuWeb(idPaginaPadre, idPlantilla);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarPaginasMenuWebAsync(int idPaginaPadre, int idPlantilla) {
            return base.Channel.ListarPaginasMenuWebAsync(idPaginaPadre, idPlantilla);
        }
        
        public System.Data.DataTable ObtenerDetallePaginaWeb(int idPagina) {
            return base.Channel.ObtenerDetallePaginaWeb(idPagina);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerDetallePaginaWebAsync(int idPagina) {
            return base.Channel.ObtenerDetallePaginaWebAsync(idPagina);
        }
        
        public System.Data.DataTable ListarGlosarioTerminosxLetraWeb(string codLetra) {
            return base.Channel.ListarGlosarioTerminosxLetraWeb(codLetra);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarGlosarioTerminosxLetraWebAsync(string codLetra) {
            return base.Channel.ListarGlosarioTerminosxLetraWebAsync(codLetra);
        }
        
        public System.Data.DataTable ListarPreguntasFrecuentesCategoriasWeb(int idPlantilla) {
            return base.Channel.ListarPreguntasFrecuentesCategoriasWeb(idPlantilla);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarPreguntasFrecuentesCategoriasWebAsync(int idPlantilla) {
            return base.Channel.ListarPreguntasFrecuentesCategoriasWebAsync(idPlantilla);
        }
        
        public System.Data.DataTable ListarPreguntasFrecuentesxCategoriaWeb(int idCategoria) {
            return base.Channel.ListarPreguntasFrecuentesxCategoriaWeb(idCategoria);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarPreguntasFrecuentesxCategoriaWebAsync(int idCategoria) {
            return base.Channel.ListarPreguntasFrecuentesxCategoriaWebAsync(idCategoria);
        }
        
        public System.Data.DataTable ListarNovedadesxTipoWeb(int idPagina, int modo) {
            return base.Channel.ListarNovedadesxTipoWeb(idPagina, modo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarNovedadesxTipoWebAsync(int idPagina, int modo) {
            return base.Channel.ListarNovedadesxTipoWebAsync(idPagina, modo);
        }
        
        public System.Data.DataTable ObtenerNovedadWeb(int idPagina_ED) {
            return base.Channel.ObtenerNovedadWeb(idPagina_ED);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerNovedadWebAsync(int idPagina_ED) {
            return base.Channel.ObtenerNovedadWebAsync(idPagina_ED);
        }
        
        public System.Data.DataTable ListarTestimonioWeb(int modo) {
            return base.Channel.ListarTestimonioWeb(modo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarTestimonioWebAsync(int modo) {
            return base.Channel.ListarTestimonioWebAsync(modo);
        }
        
        public System.Data.DataTable ObtenerTestimonioWeb(int idPagina_ED) {
            return base.Channel.ObtenerTestimonioWeb(idPagina_ED);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerTestimonioWebAsync(int idPagina_ED) {
            return base.Channel.ObtenerTestimonioWebAsync(idPagina_ED);
        }
        
        public System.Data.DataTable ListarBannersWeb(int idPlantilla) {
            return base.Channel.ListarBannersWeb(idPlantilla);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarBannersWebAsync(int idPlantilla) {
            return base.Channel.ListarBannersWebAsync(idPlantilla);
        }
        
        public System.Data.DataTable ListarPaginasArbolArchivosWeb(int idPaginaAAPadre, int idPagina) {
            return base.Channel.ListarPaginasArbolArchivosWeb(idPaginaAAPadre, idPagina);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarPaginasArbolArchivosWebAsync(int idPaginaAAPadre, int idPagina) {
            return base.Channel.ListarPaginasArbolArchivosWebAsync(idPaginaAAPadre, idPagina);
        }
        
        public System.Data.DataTable ListarPaginasxNivelWeb(int idPlantilla, int idPaginaPadre) {
            return base.Channel.ListarPaginasxNivelWeb(idPlantilla, idPaginaPadre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarPaginasxNivelWebAsync(int idPlantilla, int idPaginaPadre) {
            return base.Channel.ListarPaginasxNivelWebAsync(idPlantilla, idPaginaPadre);
        }
        
        public System.Data.DataTable ListarArbolArchivosxPaginaWeb(int idPagina) {
            return base.Channel.ListarArbolArchivosxPaginaWeb(idPagina);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarArbolArchivosxPaginaWebAsync(int idPagina) {
            return base.Channel.ListarArbolArchivosxPaginaWebAsync(idPagina);
        }
        
        public int RegistrarTestimonioWeb(string cTitular, string cImagen, string cDescripion) {
            return base.Channel.RegistrarTestimonioWeb(cTitular, cImagen, cDescripion);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarTestimonioWebAsync(string cTitular, string cImagen, string cDescripion) {
            return base.Channel.RegistrarTestimonioWebAsync(cTitular, cImagen, cDescripion);
        }
        
        public System.Data.DataTable ListarProyectosWeb(string cTipoProy) {
            return base.Channel.ListarProyectosWeb(cTipoProy);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarProyectosWebAsync(string cTipoProy) {
            return base.Channel.ListarProyectosWebAsync(cTipoProy);
        }
        
        public int RegistrarDatosContactenosWeb(
                    string cNombres, 
                    string cApellidos, 
                    int idTipoDoc, 
                    string cTipoDocDesc, 
                    string cNumeroDoc, 
                    string cEmail, 
                    string cTelefono, 
                    int idPais, 
                    string cPaisDesc, 
                    int idDepartamento, 
                    string cDepartamentoDesc, 
                    int idProvincia, 
                    string cProvinciaDesc, 
                    int idDistrito, 
                    string cDistritoDesc, 
                    int idConsulta, 
                    string cConsultaDesc, 
                    string cMedioDesc, 
                    int idMedio, 
                    string cDetalleConsultaDesc, 
                    int nDatosPersonales, 
                    int idProducto, 
                    string cProductoDesc, 
                    int idZonaInteres, 
                    string cZonaInteresDesc, 
                    int idPlazoComprar, 
                    string cPlazoComprarDesc, 
                    int idCuotaInicial, 
                    string cCuotaInicialDesc, 
                    string cRecibirEmail) {
            return base.Channel.RegistrarDatosContactenosWeb(cNombres, cApellidos, idTipoDoc, cTipoDocDesc, cNumeroDoc, cEmail, cTelefono, idPais, cPaisDesc, idDepartamento, cDepartamentoDesc, idProvincia, cProvinciaDesc, idDistrito, cDistritoDesc, idConsulta, cConsultaDesc, cMedioDesc, idMedio, cDetalleConsultaDesc, nDatosPersonales, idProducto, cProductoDesc, idZonaInteres, cZonaInteresDesc, idPlazoComprar, cPlazoComprarDesc, idCuotaInicial, cCuotaInicialDesc, cRecibirEmail);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarDatosContactenosWebAsync(
                    string cNombres, 
                    string cApellidos, 
                    int idTipoDoc, 
                    string cTipoDocDesc, 
                    string cNumeroDoc, 
                    string cEmail, 
                    string cTelefono, 
                    int idPais, 
                    string cPaisDesc, 
                    int idDepartamento, 
                    string cDepartamentoDesc, 
                    int idProvincia, 
                    string cProvinciaDesc, 
                    int idDistrito, 
                    string cDistritoDesc, 
                    int idConsulta, 
                    string cConsultaDesc, 
                    string cMedioDesc, 
                    int idMedio, 
                    string cDetalleConsultaDesc, 
                    int nDatosPersonales, 
                    int idProducto, 
                    string cProductoDesc, 
                    int idZonaInteres, 
                    string cZonaInteresDesc, 
                    int idPlazoComprar, 
                    string cPlazoComprarDesc, 
                    int idCuotaInicial, 
                    string cCuotaInicialDesc, 
                    string cRecibirEmail) {
            return base.Channel.RegistrarDatosContactenosWebAsync(cNombres, cApellidos, idTipoDoc, cTipoDocDesc, cNumeroDoc, cEmail, cTelefono, idPais, cPaisDesc, idDepartamento, cDepartamentoDesc, idProvincia, cProvinciaDesc, idDistrito, cDistritoDesc, idConsulta, cConsultaDesc, cMedioDesc, idMedio, cDetalleConsultaDesc, nDatosPersonales, idProducto, cProductoDesc, idZonaInteres, cZonaInteresDesc, idPlazoComprar, cPlazoComprarDesc, idCuotaInicial, cCuotaInicialDesc, cRecibirEmail);
        }
        
        public int RegistrarDatosReclamosWeb(
                    string cNombres, 
                    string cApellidos, 
                    int idTipoDoc, 
                    string cTipoDocDesc, 
                    string cNumeroDoc, 
                    string cEmail, 
                    string cTelefono, 
                    string cDireccion, 
                    int idPais, 
                    string cPaisDesc, 
                    int idDepartamento, 
                    string cDepartamentoDesc, 
                    int idProvincia, 
                    string cProvinciaDesc, 
                    int idDistrito, 
                    string cDistritoDesc, 
                    int idReclamoDirigido, 
                    string cReclamoDirigidoDesc, 
                    string cDetalleReclamoDesc, 
                    int nDatosPersonales, 
                    string cNumeroruc, 
                    string cRazonSocial, 
                    string cNumeroticket) {
            return base.Channel.RegistrarDatosReclamosWeb(cNombres, cApellidos, idTipoDoc, cTipoDocDesc, cNumeroDoc, cEmail, cTelefono, cDireccion, idPais, cPaisDesc, idDepartamento, cDepartamentoDesc, idProvincia, cProvinciaDesc, idDistrito, cDistritoDesc, idReclamoDirigido, cReclamoDirigidoDesc, cDetalleReclamoDesc, nDatosPersonales, cNumeroruc, cRazonSocial, cNumeroticket);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarDatosReclamosWebAsync(
                    string cNombres, 
                    string cApellidos, 
                    int idTipoDoc, 
                    string cTipoDocDesc, 
                    string cNumeroDoc, 
                    string cEmail, 
                    string cTelefono, 
                    string cDireccion, 
                    int idPais, 
                    string cPaisDesc, 
                    int idDepartamento, 
                    string cDepartamentoDesc, 
                    int idProvincia, 
                    string cProvinciaDesc, 
                    int idDistrito, 
                    string cDistritoDesc, 
                    int idReclamoDirigido, 
                    string cReclamoDirigidoDesc, 
                    string cDetalleReclamoDesc, 
                    int nDatosPersonales, 
                    string cNumeroruc, 
                    string cRazonSocial, 
                    string cNumeroticket) {
            return base.Channel.RegistrarDatosReclamosWebAsync(cNombres, cApellidos, idTipoDoc, cTipoDocDesc, cNumeroDoc, cEmail, cTelefono, cDireccion, idPais, cPaisDesc, idDepartamento, cDepartamentoDesc, idProvincia, cProvinciaDesc, idDistrito, cDistritoDesc, idReclamoDirigido, cReclamoDirigidoDesc, cDetalleReclamoDesc, nDatosPersonales, cNumeroruc, cRazonSocial, cNumeroticket);
        }
        
        public System.Data.DataTable ObtenerParametros(string scodGrupo) {
            return base.Channel.ObtenerParametros(scodGrupo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerParametrosAsync(string scodGrupo) {
            return base.Channel.ObtenerParametrosAsync(scodGrupo);
        }
        
        public System.Data.DataTable ObtenerListaET(string sRazonSocial, string sRUC, string sDepartamento, string sClasificacion) {
            return base.Channel.ObtenerListaET(sRazonSocial, sRUC, sDepartamento, sClasificacion);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerListaETAsync(string sRazonSocial, string sRUC, string sDepartamento, string sClasificacion) {
            return base.Channel.ObtenerListaETAsync(sRazonSocial, sRUC, sDepartamento, sClasificacion);
        }
        
        public System.Data.DataTable ObtenerEntidades() {
            return base.Channel.ObtenerEntidades();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerEntidadesAsync() {
            return base.Channel.ObtenerEntidadesAsync();
        }
        
        public string RegistrarRutaArchivosReclamosWeb(string oDatosRutaArchivoReclamosWeb) {
            return base.Channel.RegistrarRutaArchivosReclamosWeb(oDatosRutaArchivoReclamosWeb);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarRutaArchivosReclamosWebAsync(string oDatosRutaArchivoReclamosWeb) {
            return base.Channel.RegistrarRutaArchivosReclamosWebAsync(oDatosRutaArchivoReclamosWeb);
        }
        
        public string ActualizarReclamoconOTRSReclamo(int numeroidTickePortalweb, string numeroTicketOTRSReclamo) {
            return base.Channel.ActualizarReclamoconOTRSReclamo(numeroidTickePortalweb, numeroTicketOTRSReclamo);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarReclamoconOTRSReclamoAsync(int numeroidTickePortalweb, string numeroTicketOTRSReclamo) {
            return base.Channel.ActualizarReclamoconOTRSReclamoAsync(numeroidTickePortalweb, numeroTicketOTRSReclamo);
        }
    }
}
